# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFinancialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this financial rule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this rule does')),
                ('rule_type', models.CharField(choices=[('loan_payment', 'Loan Payment'), ('contact_based', 'Contact Based'), ('general', 'General')], help_text='Type of financial rule', max_length=50)),
                ('priority', models.IntegerField(default=100, help_text='Rule evaluation priority (lower numbers = higher priority)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('condition_logic', models.CharField(choices=[('and', 'AND - All conditions must be true'), ('or', 'OR - Any condition can be true')], default='and', help_text='How multiple conditions are evaluated', max_length=10)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this rule has been applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='financial_rules', to='company.company')),
            ],
            options={
                'verbose_name': 'Financial Rule',
                'verbose_name_plural': 'Financial Rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('amount', 'Transaction Amount'), ('description', 'Transaction Description'), ('contact', 'Contact/Payee'), ('reference', 'Reference Number'), ('date', 'Transaction Date')], help_text='Transaction field to evaluate', max_length=50)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('startswith', 'Starts With'), ('endswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('regex', 'Regular Expression')], help_text='Comparison operator', max_length=20)),
                ('value', models.CharField(help_text='Value to compare against', max_length=255)),
                ('case_sensitive', models.BooleanField(default=False, help_text='Whether string comparisons are case sensitive')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='financial_rules.basefinancialrule')),
            ],
            options={
                'verbose_name': 'Rule Condition',
                'verbose_name_plural': 'Rule Conditions',
            },
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('allocate_fixed_amount', 'Allocate Fixed Amount'), ('allocate_percentage', 'Allocate Percentage'), ('allocate_remainder', 'Allocate Remainder'), ('allocate_full_amount', 'Allocate Full Amount')], help_text='Type of allocation action', max_length=50)),
                ('target_account', models.CharField(help_text='Account code to allocate to', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount to allocate (for fixed_amount type)', max_digits=15, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage to allocate (for percentage type)', max_digits=5, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional parameters for the action')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='financial_rules.basefinancialrule')),
            ],
            options={
                'verbose_name': 'Rule Action',
                'verbose_name_plural': 'Rule Actions',
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.JSONField(help_text='Transaction data that was processed')),
                ('output_data', models.JSONField(blank=True, help_text='Result of rule execution', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the rule execution was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='financial_rules.basefinancialrule')),
            ],
            options={
                'verbose_name': 'Rule Execution Log',
                'verbose_name_plural': 'Rule Execution Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
