# Generated by Django 5.2.6 on 2025-09-07 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, help_text='Journal entry description', null=True, verbose_name='Narration')),
                ('reference', models.CharField(blank=True, help_text='External reference number', max_length=50, null=True, verbose_name='Reference')),
                ('date', models.DateField(verbose_name='Journal Date')),
                ('auto_reversing_date', models.DateField(blank=True, help_text='Date to automatically reverse this journal', null=True, verbose_name='Auto Reversing Date')),
                ('cash_basis', models.BooleanField(default=True, help_text='Show on cash basis reports', verbose_name='Cash Basis')),
                ('amount_mode', models.CharField(default='No Tax', max_length=50, verbose_name='Amount Mode')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Journal',
                'verbose_name_plural': 'Manual Journals',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('account_code', models.CharField(max_length=20, verbose_name='Account Code')),
                ('tax_rate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Rate')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debit Amount')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Credit Amount')),
                ('line_order', models.PositiveIntegerField(default=0, verbose_name='Line Order')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal.journal')),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
                'ordering': ['line_order'],
            },
        ),
    ]
