# Generated by Django 5.2.6 on 2025-09-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this journal belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='company.company'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this journal line belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='company.company'),
        ),
    ]
