# Generated by Django 5.2.6 on 2025-09-15 10:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0007_add_system_defined_tax_rates'),
        ('company', '0002_company_address_company_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_date', models.DateField(help_text='Date when you began processing transactions in this system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_date', to='company.company')),
            ],
            options={
                'verbose_name': 'Conversion Date',
                'verbose_name_plural': 'Conversion Dates',
            },
        ),
        migrations.CreateModel(
            name='ConversionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('current_year', 'Current Year'), ('previous_year', 'Previous Year'), ('last_6_months', 'Last 6 Months'), ('last_3_months', 'Last 3 Months'), ('custom', 'Custom Period')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_periods', to='company.company')),
            ],
            options={
                'verbose_name': 'Conversion Period',
                'verbose_name_plural': 'Conversion Periods',
                'ordering': ['-is_active', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ConversionBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_at_date', models.DateField(help_text='Date for which this opening balance is valid')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit opening balance', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit opening balance', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this opening balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_balances', to='coa.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_balances', to='company.company')),
            ],
            options={
                'verbose_name': 'Conversion Balance',
                'verbose_name_plural': 'Conversion Balances',
                'ordering': ['account__code', 'account__name'],
                'unique_together': {('company', 'account', 'as_at_date')},
            },
        ),
    ]
