# Generated by Django 5.2.6 on 2025-10-01 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('smart_learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patternanalytics',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='smart_learning.matchpattern'),
        ),
        migrations.AddField(
            model_name='reconciliationmetrics',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_metrics', to='company.company'),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_health', to='company.company'),
        ),
        migrations.AddField(
            model_name='userperformance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_performance', to='company.company'),
        ),
        migrations.AddField(
            model_name='userperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='patternanalytics',
            unique_together={('pattern', 'date', 'company')},
        ),
        migrations.AddIndex(
            model_name='reconciliationmetrics',
            index=models.Index(fields=['company', '-date'], name='analytics_r_company_859aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmetrics',
            index=models.Index(fields=['-date'], name='analytics_r_date_bf54f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationmetrics',
            unique_together={('date', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='systemhealth',
            unique_together={('date', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='userperformance',
            unique_together={('user', 'date', 'company')},
        ),
    ]
