# Generated by Django 5.2.6 on 2025-09-19 06:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('loans_payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_name', models.CharField(help_text="Policy name (e.g., 'Standard Consumer Loans')", max_length=100)),
                ('description', models.TextField(help_text='Description of when to use this policy')),
                ('is_default', models.BooleanField(default=False, help_text='Default policy for new loans')),
                ('allocation_method', models.CharField(choices=[('interest_first', 'Interest First (Industry Standard)'), ('principal_first', 'Principal First'), ('proportional', 'Proportional Interest/Principal'), ('customer_directed', 'Customer Directed')], default='interest_first', max_length=20)),
                ('allow_customer_directed', models.BooleanField(default=False)),
                ('prepayment_to_principal', models.BooleanField(default=True)),
                ('grace_period_days', models.IntegerField(default=10, help_text='Days before late fees are assessed')),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Fixed late fee amount', max_digits=8)),
                ('late_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.05'), help_text='Late fee as percentage of payment amount (0.05 = 5%)', max_digits=5)),
                ('use_percentage_fee', models.BooleanField(default=False, help_text='Use percentage fee instead of fixed amount')),
                ('max_late_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum late fee amount when using percentage', max_digits=8)),
                ('weekend_posting', models.CharField(choices=[('same_day', 'Same Day'), ('next_business_day', 'Next Business Day'), ('previous_business_day', 'Previous Business Day')], default='next_business_day', max_length=25)),
                ('cutoff_time', models.TimeField(default='17:00', help_text='Daily cutoff time for same-day posting')),
                ('daily_interest_calculation', models.BooleanField(default=True, help_text='Calculate interest daily vs monthly')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(help_text='Company this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', '-is_default', 'policy_name'],
                'indexes': [models.Index(fields=['company', 'is_default', 'is_active'], name='loans_payme_company_15948e_idx'), models.Index(fields=['company', 'is_active'], name='loans_payme_company_498cc2_idx')],
                'unique_together': {('company', 'policy_name')},
            },
        ),
    ]
