# Generated by Django 5.2.6 on 2025-09-28 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0006_banktransaction_transaction_datetime'),
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('loans_core', '0002_initial'),
        ('loans_customers', '0003_alter_customer_national_id'),
        ('loans_payments', '0002_paymentpolicy'),
        ('loans_schedule', '0001_initial'),
        ('reconciliation', '0005_add_company_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, help_text='Linked bank transaction (reconciliation source only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='bank_accounts.banktransaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_verification_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was bank-verified', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('bulk_upload', 'Bulk Upload'), ('reconciliation', 'Bank Reconciliation'), ('api', 'API Integration')], db_index=True, default='manual', help_text='Source of payment data entry', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_bank_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='True if payment verified against bank statement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_notes',
            field=models.TextField(blank=True, help_text='Internal notes from bank reconciliation process'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Awaiting Reconciliation'), ('matched', 'Bank Reconciled'), ('unmatched', 'Reconciliation Failed'), ('final', 'Final/Audited')], db_index=True, default='not_required', help_text='Status of bank reconciliation process', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_match',
            field=models.ForeignKey(blank=True, help_text='Reconciliation match record reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='reconciliation.transactionmatch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified payment against bank statement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loan_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'data_source', 'payment_date'], name='loans_payme_company_b48178_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'reconciliation_status'], name='loans_payme_company_96fb37_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'is_bank_verified', 'payment_date'], name='loans_payme_company_a1a3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank_transaction'], name='loans_payme_bank_tr_d192aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_match'], name='loans_payme_transac_7a37d4_idx'),
        ),
    ]
