# Generated by Django 5.2.6 on 2025-09-19 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_customers', '0002_alter_customer_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='National ID must contain only numbers, letters, and dashes', regex='^[0-9A-Za-z\\-]+$')]),
        ),
    ]
