# Generated by Django 5.2.6 on 2025-10-01 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_customers', '0003_alter_customer_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='National ID must contain only letters, numbers, and dashes', regex='^[0-9A-Za-zА-Яа-яЁё\\-]+$')]),
        ),
    ]
