# Generated by Django 5.2.6 on 2025-10-01 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0008_account_is_bank_account'),
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('loans_customers', '0004_alter_customer_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g., 'Monthly Rent Payment', 'Salary Deposits'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional: Explain when this rule applies and what it does')),
                ('match_logic', models.CharField(choices=[('ALL', 'All Conditions Must Match (AND)'), ('ANY', 'Any Condition Can Match (OR)')], default='ALL', help_text='How to combine multiple conditions', max_length=10)),
                ('suggested_what', models.CharField(blank=True, help_text='Auto-suggest this description (WHAT field)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Disable rule without deleting it')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first (0-100, default: 0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_matched', models.IntegerField(default=0, help_text='How many times this rule has matched transactions')),
                ('last_matched', models.DateTimeField(blank=True, help_text='Last time this rule matched a transaction', null=True)),
                ('company', models.ForeignKey(help_text='Company that owns this rule', on_delete=django.db.models.deletion.CASCADE, related_name='bank_rules', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_rules', to=settings.AUTH_USER_MODEL)),
                ('suggested_coa', models.ForeignKey(blank=True, help_text='Auto-suggest this COA account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_rules_suggesting', to='coa.account')),
                ('suggested_who', models.ForeignKey(blank=True, help_text='Auto-suggest this customer (WHO field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_rules_suggesting', to='loans_customers.customer')),
            ],
            options={
                'verbose_name': 'Bank Rule',
                'verbose_name_plural': 'Bank Rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('description', 'Transaction Description'), ('amount', 'Amount (Exact)'), ('amount_abs', 'Amount (Absolute Value)'), ('debit_credit', 'Debit or Credit'), ('correspondent_account', 'Correspondent Account'), ('date', 'Transaction Date'), ('reference', 'Reference Number')], help_text='Which transaction field to check', max_length=50)),
                ('operator', models.CharField(choices=[('equals', 'Equals (exact match)'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('is_blank', 'Is Blank/Empty'), ('is_not_blank', 'Is Not Blank'), ('greater_than', 'Greater Than (>)'), ('less_than', 'Less Than (<)'), ('greater_equal', 'Greater or Equal (≥)'), ('less_equal', 'Less or Equal (≤)'), ('between', 'Between (range)')], help_text='How to compare the field value', max_length=50)),
                ('value', models.CharField(blank=True, help_text="Primary value (or lower bound for 'between')", max_length=500)),
                ('value_secondary', models.CharField(blank=True, help_text="Upper bound for 'between' operator only", max_length=500)),
                ('case_sensitive', models.BooleanField(default=False, help_text='Match case exactly (usually keep OFF for flexibility)')),
                ('order', models.IntegerField(default=0, help_text='Display order in rule builder')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bank_rules.bankrule')),
            ],
            options={
                'verbose_name': 'Rule Condition',
                'verbose_name_plural': 'Rule Conditions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankrule',
            index=models.Index(fields=['company', 'is_active'], name='bank_rules__company_7d9ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='bankrule',
            index=models.Index(fields=['-priority'], name='bank_rules__priorit_26e8f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankrule',
            unique_together={('company', 'name')},
        ),
    ]
