# Generated by Django 5.2.6 on 2025-10-01 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_rules', '0001_initial'),
        ('coa', '0008_account_is_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrule',
            name='suggested_what',
        ),
        migrations.RemoveField(
            model_name='bankrule',
            name='suggested_who',
        ),
        migrations.AddField(
            model_name='bankrule',
            name='suggested_who_text',
            field=models.CharField(blank=True, help_text='Auto-suggest this correspondent name (WHO field) - can be any text', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankrule',
            name='suggested_coa',
            field=models.ForeignKey(blank=True, help_text='Auto-suggest this Chart of Account (WHAT field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_rules_suggesting', to='coa.account'),
        ),
    ]
