# Generated by Django 5.2.6 on 2025-09-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_info_complete', models.BooleanField(default=False)),
                ('accounts_complete', models.BooleanField(default=False)),
                ('tax_complete', models.BooleanField(default=False)),
                ('opening_balance_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_status', to='company.company')),
            ],
            options={
                'verbose_name': 'Company Setup Status',
                'verbose_name_plural': 'Company Setup Status',
            },
        ),
    ]
