# Generated by Django 5.2.6 on 2025-09-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysetupstatus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Company Setup Status', 'verbose_name_plural': 'Company Setup Statuses'},
        ),
        migrations.RemoveField(
            model_name='companysetupstatus',
            name='opening_balance_complete',
        ),
        migrations.AddField(
            model_name='companysetupstatus',
            name='balance_complete',
            field=models.BooleanField(default=False, help_text='Opening balances entered', verbose_name='Opening Balances Complete'),
        ),
        migrations.AddField(
            model_name='companysetupstatus',
            name='current_step',
            field=models.CharField(blank=True, help_text='Current setup step being worked on', max_length=50, verbose_name='Current Step'),
        ),
        migrations.AddField(
            model_name='companysetupstatus',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about setup process', verbose_name='Setup Notes'),
        ),
        migrations.AddField(
            model_name='companysetupstatus',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, help_text='When setup process was completed', null=True, verbose_name='Setup Completed At'),
        ),
        migrations.AddField(
            model_name='companysetupstatus',
            name='setup_started_at',
            field=models.DateTimeField(blank=True, help_text='When setup process was first started', null=True, verbose_name='Setup Started At'),
        ),
        migrations.AlterField(
            model_name='companysetupstatus',
            name='accounts_complete',
            field=models.BooleanField(default=False, help_text='Essential accounts created', verbose_name='Essential Accounts Complete'),
        ),
        migrations.AlterField(
            model_name='companysetupstatus',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_status', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companysetupstatus',
            name='company_info_complete',
            field=models.BooleanField(default=False, help_text='Company information setup completed', verbose_name='Company Info Complete'),
        ),
        migrations.AlterField(
            model_name='companysetupstatus',
            name='tax_complete',
            field=models.BooleanField(default=False, help_text='Tax rates configured (optional step)', verbose_name='Tax Configuration Complete'),
        ),
    ]
