# Generated by Django 5.2.6 on 2025-09-29 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Type name (e.g., 'Residential Property')", max_length=100)),
                ('category', models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment & Machinery'), ('securities', 'Securities & Investments'), ('inventory', 'Inventory & Stock'), ('cash_deposit', 'Cash Deposit'), ('other', 'Other Assets')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_loan_to_value', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Maximum LTV ratio as percentage (e.g., 80.00 for 80%)', max_digits=5)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Annual depreciation rate as percentage', max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='medium', max_length=20)),
                ('liquidity_score', models.IntegerField(default=5, help_text='Liquidity score (1=Very Illiquid, 10=Very Liquid)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('requires_insurance', models.BooleanField(default=False)),
                ('requires_professional_valuation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collateral Type',
                'verbose_name_plural': 'Collateral Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Brief title describing the collateral', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the collateral item')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('owner_name', models.CharField(max_length=200)),
                ('ownership_document', models.CharField(blank=True, max_length=500, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('declared_value', models.DecimalField(decimal_places=2, help_text='Value declared by applicant', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current market value assessment', max_digits=12, null=True)),
                ('loan_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value acceptable for loan calculation (after LTV ratio)', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('valued', 'Professionally Valued'), ('approved', 'Approved for Collateral'), ('rejected', 'Rejected'), ('released', 'Released')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('insurance_required', models.BooleanField(default=False)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_items', to='loans_core.loanapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_collateral', to=settings.AUTH_USER_MODEL)),
                ('collateral_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans_collateral.collateraltype')),
            ],
            options={
                'verbose_name': 'Collateral',
                'verbose_name_plural': 'Collateral Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollateralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ownership', 'Ownership Certificate'), ('title_deed', 'Title Deed'), ('registration', 'Registration Document'), ('insurance', 'Insurance Policy'), ('valuation', 'Valuation Report'), ('photos', 'Photographs'), ('inspection', 'Inspection Report'), ('legal_opinion', 'Legal Opinion'), ('other', 'Other Document')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='collateral/documents/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans_collateral.collateral')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collateral Document',
                'verbose_name_plural': 'Collateral Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CollateralValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_type', models.CharField(choices=[('initial', 'Initial Valuation'), ('annual_review', 'Annual Review'), ('market_update', 'Market Update'), ('damage_assessment', 'Damage Assessment'), ('disposal', 'Disposal Valuation')], max_length=20)),
                ('valuer_type', models.CharField(choices=[('internal', 'Internal Valuation'), ('external', 'External Professional'), ('automated', 'Automated System')], max_length=20)),
                ('valuer_name', models.CharField(max_length=200)),
                ('valuer_license', models.CharField(blank=True, max_length=100, null=True)),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('forced_sale_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value in forced sale scenario', max_digits=12, null=True)),
                ('valuation_date', models.DateField()),
                ('report_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('methodology', models.TextField(blank=True, null=True)),
                ('key_assumptions', models.TextField(blank=True, null=True)),
                ('limitations', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateField(help_text='Valuation validity expiry date')),
                ('is_current', models.BooleanField(default=True)),
                ('report_file', models.FileField(blank=True, help_text='Upload valuation report PDF', null=True, upload_to='collateral/valuations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='loans_collateral.collateral')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collateral Valuation',
                'verbose_name_plural': 'Collateral Valuations',
                'ordering': ['-valuation_date'],
            },
        ),
    ]
