# Generated by Django 5.2.6 on 2025-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_collateral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='vehicle_fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('cng', 'CNG'), ('lpg', 'LPG')], help_text='Type of fuel used', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='vehicle_license_plate',
            field=models.CharField(blank=True, help_text='License plate number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle manufacturer (e.g., Toyota, BMW)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='vehicle_mileage',
            field=models.IntegerField(blank=True, help_text='Current mileage/odometer reading', null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., Camry, X5)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='vehicle_registration_year',
            field=models.IntegerField(blank=True, help_text='Year of first registration', null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='vehicle_vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number (VIN)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='vehicle_year',
            field=models.IntegerField(blank=True, help_text='Year of manufacture', null=True),
        ),
    ]
