# Generated by Django 5.2.6 on 2025-09-16 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('loans_core', '0001_initial'),
        ('loans_customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans_customers.customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans_customers.customer'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loans_core.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans_core.loanproduct'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans_core.loanproduct'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['company', 'category', 'is_active'], name='loans_core__company_ae8694_idx'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['company', 'code'], name='loans_core__company_10df76_idx'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['company', 'is_active'], name='loans_core__company_662e49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanproduct',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['company', 'customer', 'status'], name='loans_core__company_054a21_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['company', 'application_id'], name='loans_core__company_2b32aa_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['company', 'status', 'application_date'], name='loans_core__company_5c2d79_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['company', 'assigned_officer'], name='loans_core__company_7eff7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanapplication',
            unique_together={('company', 'application_id')},
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['company', 'customer', 'status'], name='loans_core__company_093fae_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['company', 'loan_number'], name='loans_core__company_bde59f_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['company', 'status', 'next_payment_date'], name='loans_core__company_5ded27_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['company', 'days_overdue'], name='loans_core__company_0ce1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['company', 'application'], name='loans_core__company_20abed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('company', 'loan_number')},
        ),
    ]
