# Generated by Django 5.2.6 on 2025-09-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0003_banktransaction_transaction_hash_uploadedfile'),
        ('coa', '0007_add_system_defined_tax_rates'),
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Name or description of this reconciliation', max_length=200)),
                ('statement_date', models.DateField(help_text='Statement ending date')),
                ('statement_balance', models.DecimalField(decimal_places=2, help_text='Statement ending balance', max_digits=15)),
                ('reconciled_balance', models.DecimalField(decimal_places=2, default=0, help_text='Reconciled balance', max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='Difference between statement and reconciled', max_digits=15)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('balanced', 'Balanced'), ('unbalanced', 'Unbalanced'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type': 'Bank'}, on_delete=django.db.models.deletion.CASCADE, to='coa.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bank_transactions', models.IntegerField(default=0)),
                ('total_reconciled', models.IntegerField(default=0)),
                ('total_unreconciled', models.IntegerField(default=0)),
                ('auto_matched', models.IntegerField(default=0)),
                ('manual_matched', models.IntegerField(default=0)),
                ('report_data', models.JSONField(default=dict, help_text='Detailed report data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.reconciliationsession')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_confidence', models.DecimalField(decimal_places=2, default=0, help_text='Auto-match confidence %', max_digits=5)),
                ('is_manual_match', models.BooleanField(default=False, help_text='Was this match done manually?')),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Reconciliation notes')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.banktransaction')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reconciliation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.reconciliationsession')),
            ],
            options={
                'unique_together': {('bank_transaction', 'reconciliation_session')},
            },
        ),
    ]
