# Generated by Django 5.2.6 on 2025-09-05 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file', models.FileField(upload_to='reconciliation/uploads/%Y/%m/%d/', verbose_name='Uploaded File')),
                ('file_size', models.IntegerField(verbose_name='File Size (bytes)')),
                ('bank_account_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Account Name')),
                ('statement_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Statement Period')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(verbose_name='Success')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transactions_extracted', models.IntegerField(default=0)),
                ('transactions_imported', models.IntegerField(default=0)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='reconciliation.uploadedfile', verbose_name='Uploaded File')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField(verbose_name='Row Number')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('payee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payee')),
                ('description', models.TextField(verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference')),
                ('who', models.CharField(blank=True, max_length=255, null=True, verbose_name='Who (Contact Name)')),
                ('what', models.CharField(blank=True, max_length=255, null=True, verbose_name='What (Account Code)')),
                ('why', models.TextField(blank=True, null=True, verbose_name='Why (Reason)')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reconciliation.uploadedfile', verbose_name='Source File')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-date', 'row_number'],
            },
        ),
    ]
