# Generated by Django 5.2.6 on 2025-09-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_banktransaction_transaction_hash_uploadedfile'),
        ('coa', '0007_add_system_defined_tax_rates'),
        ('journal', '0001_initial'),
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmatch',
            options={'ordering': ['-matched_at']},
        ),
        migrations.RemoveField(
            model_name='reconciliationsession',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='reconciliationsession',
            name='reconciled_balance',
        ),
        migrations.RemoveField(
            model_name='reconciliationsession',
            name='statement_date',
        ),
        migrations.RemoveField(
            model_name='transactionmatch',
            name='is_manual_match',
        ),
        migrations.RemoveField(
            model_name='transactionmatch',
            name='reconciled_at',
        ),
        migrations.RemoveField(
            model_name='transactionmatch',
            name='reconciled_by',
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Closing balance', max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='matched_transactions',
            field=models.IntegerField(default=0, help_text='Successfully matched transactions'),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opening balance', max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='period_end',
            field=models.DateField(blank=True, help_text='Reconciliation period end date', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='period_start',
            field=models.DateField(blank=True, help_text='Reconciliation period start date', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='total_transactions',
            field=models.IntegerField(default=0, help_text='Total transactions in this session'),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='unmatched_transactions',
            field=models.IntegerField(default=0, help_text='Unmatched transactions'),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='contact',
            field=models.CharField(blank=True, help_text='WHO - Contact/Payee name', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='description',
            field=models.TextField(blank=True, help_text='WHY - User description/memo for this transaction'),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='gl_account',
            field=models.ForeignKey(blank=True, help_text='WHAT - Chart of Account for categorization', null=True, on_delete=django.db.models.deletion.CASCADE, to='coa.account'),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='match_type',
            field=models.CharField(choices=[('manual', 'Manual Match'), ('auto', 'Auto Match'), ('partial', 'Partial Match'), ('bulk', 'Bulk Match')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='matched_at',
            field=models.DateTimeField(blank=True, help_text='When this match was created', null=True),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='matched_by',
            field=models.ForeignKey(blank=True, help_text='User who made this match', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='tax_rate',
            field=models.CharField(blank=True, help_text='TAX - GST/Tax rate applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='reconciliationsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('review', 'Under Review'), ('balanced', 'Balanced'), ('completed', 'Completed'), ('locked', 'Locked')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionmatch',
            name='bank_transaction',
            field=models.OneToOneField(help_text='Raw bank transaction', on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.banktransaction'),
        ),
        migrations.AlterField(
            model_name='transactionmatch',
            name='is_reconciled',
            field=models.BooleanField(default=True, help_text='Is this transaction fully reconciled?'),
        ),
        migrations.AlterField(
            model_name='transactionmatch',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Auto-created journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='transactionmatch',
            name='match_confidence',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Match confidence percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='transactionmatch',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional reconciliation notes'),
        ),
    ]
