# Generated by Django 5.2.6 on 2025-09-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_alter_transactionmatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationsession',
            name='statement_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Statement ending balance', max_digits=15),
        ),
    ]
