# Generated by Django 5.2.6 on 2025-09-11 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0007_add_system_defined_tax_rates'),
        ('reconciliation', '0003_fix_statement_balance_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_number', models.PositiveIntegerField(help_text='Split sequence number (1, 2, 3...)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this split', max_digits=15)),
                ('contact', models.CharField(blank=True, help_text='WHO - Contact/Payee for this split', max_length=255)),
                ('description', models.TextField(blank=True, help_text='WHY - Description for this split')),
                ('tax_rate', models.CharField(blank=True, help_text='TAX - GST/Tax rate for this split', max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount for this split', max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='Net amount (amount - tax)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(help_text='WHAT - GL Account for this split', on_delete=django.db.models.deletion.CASCADE, to='coa.account')),
                ('transaction_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='reconciliation.transactionmatch')),
            ],
            options={
                'ordering': ['split_number'],
                'unique_together': {('transaction_match', 'split_number')},
            },
        ),
    ]
