# Generated by Django 5.2.6 on 2025-09-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('reconciliation', '0004_add_transaction_split_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationreport',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this report belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_reports', to='company.company'),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this reconciliation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to='company.company'),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this transaction match belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_matches', to='company.company'),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this transaction split belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_splits', to='company.company'),
        ),
    ]
