# Generated by Django 5.2.6 on 2025-09-22 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0007_add_system_defined_tax_rates'),
        ('company', '0002_company_address_company_base_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanGLConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this configuration was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this configuration was last updated')),
                ('company', models.ForeignKey(help_text='Company this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('interest_income_account', models.ForeignKey(help_text='GL account for interest income (e.g., 4200 - Interest Income)', on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_configs', to='coa.account')),
                ('late_fee_income_account', models.ForeignKey(help_text='GL account for late fee income (e.g., 4250 - Late Fee Income)', on_delete=django.db.models.deletion.PROTECT, related_name='loan_late_fee_configs', to='coa.account')),
                ('principal_account', models.ForeignKey(help_text='GL account for loan principal payments (e.g., 1200 - Loans Receivable)', on_delete=django.db.models.deletion.PROTECT, related_name='loan_principal_configs', to='coa.account')),
            ],
            options={
                'verbose_name': 'Loan GL Configuration',
                'verbose_name_plural': 'Loan GL Configurations',
            },
        ),
        migrations.CreateModel(
            name='LoanCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Name of customer for loan payment', max_length=200)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Total payment amount', max_digits=10)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Late fee portion of payment', max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, help_text='Interest portion of payment', max_digits=10)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, help_text='Principal portion of payment', max_digits=10)),
                ('calculation_source', models.CharField(default='loan_bridge_service', help_text='Source system that performed the calculation', max_length=50)),
                ('success', models.BooleanField(default=True, help_text='Whether the calculation was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if calculation failed')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='When this calculation was performed')),
                ('calculated_by', models.ForeignKey(blank=True, help_text='User who triggered this calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Company for which calculation was performed', on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('gl_configuration', models.ForeignKey(blank=True, help_text='GL configuration used for this calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_reconciliation_bridge.loanglconfiguration')),
            ],
            options={
                'verbose_name': 'Loan Calculation Log',
                'verbose_name_plural': 'Loan Calculation Logs',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loanglconfiguration',
            index=models.Index(fields=['company', 'is_active'], name='loan_reconc_company_fa48f8_idx'),
        ),
        migrations.AddIndex(
            model_name='loanglconfiguration',
            index=models.Index(fields=['created_at'], name='loan_reconc_created_3fb680_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanglconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company',), name='unique_active_config_per_company'),
        ),
        migrations.AddIndex(
            model_name='loancalculationlog',
            index=models.Index(fields=['company', 'calculated_at'], name='loan_reconc_company_ffbc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='loancalculationlog',
            index=models.Index(fields=['customer_name', 'calculated_at'], name='loan_reconc_custome_99d55b_idx'),
        ),
        migrations.AddIndex(
            model_name='loancalculationlog',
            index=models.Index(fields=['success', 'calculated_at'], name='loan_reconc_success_153d32_idx'),
        ),
    ]
