# Generated by Django 5.2.6 on 2025-09-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0007_add_system_defined_tax_rates'),
        ('company', '0002_company_address_company_base_currency_and_more'),
        ('loan_reconciliation_bridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loanglconfiguration',
            name='unique_active_config_per_company',
        ),
        migrations.RemoveIndex(
            model_name='loancalculationlog',
            name='loan_reconc_company_ffbc5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='loancalculationlog',
            name='loan_reconc_custome_99d55b_idx',
        ),
        migrations.RemoveIndex(
            model_name='loancalculationlog',
            name='loan_reconc_success_153d32_idx',
        ),
        migrations.RemoveIndex(
            model_name='loanglconfiguration',
            name='loan_reconc_company_fa48f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='loanglconfiguration',
            name='loan_reconc_created_3fb680_idx',
        ),
        migrations.AlterField(
            model_name='loancalculationlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_calculation_logs', to='company.company'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_gl_config', to='company.company'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='interest_income_account',
            field=models.ForeignKey(blank=True, help_text='Account for interest income (e.g., 4200 - Interest Income) - Optional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_configs', to='coa.account'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='late_fee_income_account',
            field=models.ForeignKey(blank=True, help_text='Account for late fee income (e.g., 4250 - Late Fee Income) - Optional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_late_fee_configs', to='coa.account'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='principal_account',
            field=models.ForeignKey(help_text='Account for loan principal payments (e.g., 1200 - Loans Receivable)', on_delete=django.db.models.deletion.PROTECT, related_name='loan_principal_configs', to='coa.account'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
