# Generated by Django 5.2.6 on 2025-09-28 11:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0008_account_is_bank_account'),
        ('loan_reconciliation_bridge', '0002_remove_loanglconfiguration_unique_active_config_per_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanglconfiguration',
            name='default_interest_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Default percentage for interest allocation (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanglconfiguration',
            name='default_late_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default percentage for late fee allocation (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanglconfiguration',
            name='general_loans_receivable_account',
            field=models.ForeignKey(blank=True, help_text='Main account (122000) that receives loan payments and creates Payment records via reconciliation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_main_receivable_configs', to='coa.account'),
        ),
        migrations.AddField(
            model_name='loanglconfiguration',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='Whether the three-tier setup has been completed'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='interest_income_account',
            field=models.ForeignKey(blank=True, help_text='Revenue account for interest income (e.g., 4200 - Interest Income)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_configs', to='coa.account'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='late_fee_income_account',
            field=models.ForeignKey(blank=True, help_text='Revenue account for late fee income (e.g., 4250 - Late Fee Income)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_late_fee_configs', to='coa.account'),
        ),
        migrations.AlterField(
            model_name='loanglconfiguration',
            name='principal_account',
            field=models.ForeignKey(blank=True, help_text='Asset account for principal payments (can be same as General Loans Receivable or separate)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_principal_configs', to='coa.account'),
        ),
    ]
