# Generated by Django 5.2.6 on 2025-09-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0008_account_is_bank_account'),
        ('loan_reconciliation_bridge', '0004_populate_general_loans_receivable_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanglconfiguration',
            name='general_loan_disbursements_account',
            field=models.ForeignKey(blank=True, help_text='Account for automatic loan disbursement detection and matching (e.g., 1250 - Loan Disbursements)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_disbursement_configs', to='coa.account'),
        ),
    ]
