# Generated by Django 5.2.6 on 2025-09-08 06:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official company name', max_length=200)),
                ('legal_name', models.CharField(blank=True, help_text='Legal registered name if different', max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration/license number', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number (EIN, ABN, etc.)', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Primary company email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='United States', max_length=100)),
                ('base_currency', models.CharField(default='USD', help_text='Base currency code (USD, EUR, GBP, etc.)', max_length=3)),
                ('financial_year_start', models.DateField(blank=True, help_text='Start date of financial year', null=True)),
                ('business_type', models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation'), ('s_corp', 'S Corporation'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], help_text='Legal business structure', max_length=50)),
                ('industry', models.CharField(blank=True, help_text='Primary industry or sector', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCompanyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_company', models.ForeignKey(blank=True, help_text='Currently selected company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('default_company', models.ForeignKey(blank=True, help_text='Default company on login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='company.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Company Preference',
                'verbose_name_plural': 'User Company Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_edit_settings', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Company Role',
                'verbose_name_plural': 'User Company Roles',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
