# Generated by Django 5.2.6 on 2025-09-05 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tax Rate Name')),
                ('rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Enter as decimal (e.g., 0.1500 for 15%)', max_digits=5, verbose_name='Tax Rate (%)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='General Ledger account code', max_length=20, unique=True, verbose_name='GL Code')),
                ('name', models.CharField(help_text='Full account name', max_length=255, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20, verbose_name='Account Type')),
                ('ytd_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Year-to-Date balance amount', max_digits=15, verbose_name='YTD Balance')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked accounts cannot be modified', verbose_name='Is Locked')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts are hidden', verbose_name='Is Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, help_text='For sub-accounts', null=True, on_delete=django.db.models.deletion.CASCADE, to='coa.account', verbose_name='Parent Account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tax_rate', models.ForeignKey(help_text='Select applicable tax rate (Tax Exempt = 0%)', on_delete=django.db.models.deletion.PROTECT, to='coa.taxrate', verbose_name='Tax Rate')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code', 'name'],
                'indexes': [models.Index(fields=['code'], name='coa_account_code_826e72_idx'), models.Index(fields=['account_type'], name='coa_account_account_a7954d_idx'), models.Index(fields=['is_active'], name='coa_account_is_acti_7f7b02_idx')],
            },
        ),
    ]
