# Generated by Django 5.2.6 on 2025-09-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CURRENT_ASSET', 'Current Asset'), ('FIXED_ASSET', 'Fixed Asset'), ('INVENTORY', 'Inventory'), ('NON_CURRENT_ASSET', 'Non-current Asset'), ('PREPAYMENT', 'Prepayment'), ('EQUITY', 'Equity'), ('DEPRECIATION', 'Depreciation'), ('DIRECT_COST', 'Direct Cost'), ('EXPENSE', 'Expense'), ('OVERHEAD', 'Overhead'), ('CURRENT_LIABILITY', 'Current Liability'), ('LIABILITY', 'Liability'), ('NON_CURRENT_LIABILITY', 'Non-current Liability'), ('OTHER_INCOME', 'Other Income'), ('REVENUE', 'Revenue'), ('SALES', 'Sales')], max_length=25, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='A unique code/number for this account (limited to 10 characters)', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='A short title for this account (limited to 150 characters)', max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_rate',
            field=models.ForeignKey(help_text='The default tax setting for this account', on_delete=django.db.models.deletion.PROTECT, to='coa.taxrate', verbose_name='Tax'),
        ),
    ]
