# Generated by Django 5.2.6 on 2025-09-08 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_alter_account_account_type_alter_account_code_and_more'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['company', 'code', 'name'], 'verbose_name': 'Chart of Account', 'verbose_name_plural': 'Chart of Accounts'},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Tax Rate', 'verbose_name_plural': 'Tax Rates'},
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='coa_account_code_826e72_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='coa_account_account_a7954d_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='coa_account_is_acti_7f7b02_idx',
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this tax rate belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='A unique code/number for this account (limited to 10 characters)', max_length=10, verbose_name='Code'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'code'], name='coa_account_company_025066_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'account_type'], name='coa_account_company_5521f6_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_active'], name='coa_account_company_e1646a_idx'),
        ),
    ]
