# Generated by Django 5.2.6 on 2025-09-08 11:04

from django.db import migrations


def assign_existing_data_to_first_company(apps, schema_editor):
    """Assign existing COA data to the first company."""
    Company = apps.get_model('company', 'Company')
    Account = apps.get_model('coa', 'Account')
    TaxRate = apps.get_model('coa', 'TaxRate')
    
    # Get first company (should be one of the companies you created)
    first_company = Company.objects.first()
    
    if first_company:
        # Assign all existing accounts to first company
        Account.objects.filter(company__isnull=True).update(company=first_company)
        
        # Assign all existing tax rates to first company
        TaxRate.objects.filter(company__isnull=True).update(company=first_company)
        
        print(f"Assigned existing COA data to company: {first_company.name}")
    else:
        print("No companies found. Please create a company first.")


def reverse_assignment(apps, schema_editor):
    """Reverse the assignment by setting company to null."""
    Account = apps.get_model('coa', 'Account')
    TaxRate = apps.get_model('coa', 'TaxRate')
    
    Account.objects.all().update(company=None)
    TaxRate.objects.all().update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0003_alter_account_options_alter_taxrate_options_and_more'),
        ('company', '0001_initial'),  # Ensure company app migrations are applied first
    ]

    operations = [
        migrations.RunPython(
            assign_existing_data_to_first_company,
            reverse_assignment
        ),
    ]
