# Generated by Django 5.2.6 on 2025-09-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0004_assign_existing_data_to_company'),
        ('company', '0001_initial'),
    ]

    operations = [
        # Make company field required for Account
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(
                help_text='Company this account belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                to='company.company',
                verbose_name='Company'
            ),
        ),
        # Make company field required for TaxRate
        migrations.AlterField(
            model_name='taxrate',
            name='company',
            field=models.ForeignKey(
                help_text='Company this tax rate belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                to='company.company',
                verbose_name='Company'
            ),
        ),
    ]
