# Generated by Django 5.2.6 on 2025-09-08 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0005_make_company_required'),
        ('company', '0002_company_address_company_base_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, help_text='Opening balance amount', max_digits=15, verbose_name='Balance Amount')),
                ('balance_date', models.DateField(help_text='Date of the opening balance', verbose_name='Balance Date')),
                ('description', models.TextField(blank=True, help_text='Optional description for the opening balance', null=True, verbose_name='Description')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Entered At')),
                ('is_active', models.BooleanField(default=True, help_text='Active opening balances', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Opening Balance',
                'verbose_name_plural': 'Opening Balances',
                'ordering': ['company', 'account__code', 'balance_date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance for this account', max_digits=15, verbose_name='Current Balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_essential',
            field=models.BooleanField(default=False, help_text='Account created during essential setup process', verbose_name='Essential Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance for this account', max_digits=15, verbose_name='Opening Balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='setup_category',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Account'), ('income', 'Income Account'), ('expense', 'Expense Account'), ('equity', 'Equity Account')], help_text='Setup category for essential accounts', max_length=50),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default tax rate for this company', verbose_name='Default Tax Rate'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='setup_created',
            field=models.BooleanField(default=False, help_text='Tax rate created during company setup process', verbose_name='Created During Setup'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_authority',
            field=models.CharField(blank=True, help_text='Tax collection authority', max_length=100),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('sales_tax', 'Sales Tax'), ('vat', 'Value Added Tax (VAT)'), ('gst', 'Goods & Services Tax (GST)'), ('excise', 'Excise Tax'), ('other', 'Other')], help_text='Type of tax', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, help_text='A description of how this account should be used (optional)', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_rate',
            field=models.ForeignKey(blank=True, help_text='The default tax setting for this account', null=True, on_delete=django.db.models.deletion.PROTECT, to='coa.taxrate', verbose_name='Tax'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_essential', 'setup_category'], name='coa_account_company_1ad282_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'tax_rate'], name='coa_account_company_e8528d_idx'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='account',
            field=models.ForeignKey(help_text='Account for this opening balance', on_delete=django.db.models.deletion.CASCADE, to='coa.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='company',
            field=models.ForeignKey(help_text='Company this opening balance belongs to', on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='entered_by',
            field=models.ForeignKey(help_text='User who entered this opening balance', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Entered By'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['company', 'account'], name='coa_opening_company_3c8f06_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['company', 'balance_date'], name='coa_opening_company_a42c73_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['company', 'is_active'], name='coa_opening_company_249acb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openingbalance',
            unique_together={('company', 'account')},
        ),
    ]
