# Generated by Django 5.2.6 on 2025-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0006_openingbalance_account_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='is_system_defined',
            field=models.BooleanField(default=False, help_text='System defined tax rates cannot be deleted', verbose_name='System Defined'),
        ),
    ]
