# Generated by Django 5.2.6 on 2025-09-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0007_add_system_defined_tax_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_bank_account',
            field=models.BooleanField(default=False, help_text='Mark this CURRENT_ASSET account as a bank account for bank management features', verbose_name='Is Bank Account'),
        ),
    ]
