# Generated by Django 5.2.6 on 2025-09-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_banktransaction_transaction_hash_uploadedfile'),
        ('company', '0002_company_address_company_base_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this transaction belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='company.company'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='company.company'),
        ),
    ]
