# Generated by Django 5.2.6 on 2025-09-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0005_bankstatementdocument_bankstatementprocessing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_datetime',
            field=models.DateTimeField(blank=True, help_text='Full transaction date and time if available', null=True),
        ),
    ]
