# Generated by Django 5.2.6 on 2025-09-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0006_banktransaction_transaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='related_account',
            field=models.CharField(blank=True, help_text='Харьцсан данс - Related account number from column H', max_length=20),
        ),
    ]
