# Generated by Django 5.2.6 on 2025-09-30 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0007_banktransaction_related_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='AI confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name extracted from description', max_length=200),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='loan_number',
            field=models.CharField(blank=True, help_text='Loan number if detected', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='processing_method',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'File Import'), ('smart_ai', 'Smart AI Processing')], default='manual', help_text='How this transaction was processed', max_length=20),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='suggestion_feedback',
            field=models.CharField(blank=True, choices=[('good', 'Good Match'), ('poor', 'Poor Match'), ('corrected', 'User Corrected')], help_text='User feedback on AI suggestion quality', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('auto', 'Auto-Detected'), ('disbursement', 'Loan Disbursement'), ('payment', 'Loan Payment'), ('other', 'Other')], default='auto', help_text='Type of transaction', max_length=20),
        ),
    ]
