# Generated by Django 5.2.6 on 2025-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0009_add_smart_processing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='date_from',
            field=models.DateField(blank=True, help_text='First transaction date in this file', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='date_to',
            field=models.DateField(blank=True, help_text='Last transaction date in this file', null=True),
        ),
    ]
